version: v0
services:
  - name: localhub
    image: baetyl-hub
    replica: 1
    mounts:
      - name: localhub-conf
        path: etc/baetyl
        readonly: true
      - name: localhub-data
        path: var/db/baetyl/data
      - name: localhub-log
        path: var/log/baetyl
      # native process mode only
      - name: baetyl-hub-bin
        path: lib/baetyl/baetyl-hub
        readonly: true
  - name: function-manager
    image: baetyl-function-manager
    replica: 1
    mounts:
      - name: function-manager-conf
        path: etc/baetyl
        readonly: true
      - name: function-manager-log
        path: var/log/baetyl
      # native process mode only
      - name: baetyl-function-manager-bin
        path: lib/baetyl/baetyl-function-manager
        readonly: true
  - name: video-infer
    image: baetyl-video-infer
    replica: 1
    mounts:
      - name: video-infer-conf
        path: etc/baetyl
        readonly: true
      - name: video-infer-model
        path: var/db/baetyl/model
        readonly: true
      - name: video-infer-image
        path: var/db/baetyl/image
      - name: video-infer-log
        path: var/log/baetyl
      # native process mode only
      - name: baetyl-video-infer-bin
        path: lib/baetyl/baetyl-video-infer
        readonly: true
  - name: function-python
    image: baetyl-function-python36
    replica: 0
    mounts:
      - name: function-python-conf
        path: etc/baetyl
        readonly: true
      - name: function-python-code
        path: var/db/baetyl/code
        readonly: true
      - name: video-infer-image
        path: var/db/baetyl/image
      - name: function-python-log
        path: var/db/baetyl/log
      # native process mode only
      - name: baetyl-function-python36-bin
        path: lib/baetyl/baetyl-function-python36
        readonly: true
volumes:
  # hub
  - name: localhub-conf
    path: var/db/baetyl/localhub-conf
  - name: localhub-data
    path: var/db/baetyl/localhub-data
  - name: localhub-log
    path: var/db/baetyl/localhub-log
  # function
  - name: function-manager-conf
    path: var/db/baetyl/function-manager-conf
  - name: function-manager-log
    path: var/db/baetyl/function-manager-log
  - name: function-python-conf
    path: var/db/baetyl/function-python-conf
  - name: function-python-code
    path: var/db/baetyl/function-python-code
  - name: function-python-log
    path: var/db/baetyl/function-python-log
  # video infer
  - name: video-infer-conf
    path: var/db/baetyl/video-infer-conf
  - name: video-infer-model
    path: var/db/baetyl/video-infer-model
  - name: video-infer-image
    path: var/db/baetyl/video-infer-image
  - name: video-infer-log
    path: var/db/baetyl/video-infer-log
  # bin, native process mode only
  - name: baetyl-hub-bin
    path: var/db/baetyl/baetyl-hub
  - name: baetyl-function-manager-bin
    path: var/db/baetyl/baetyl-function-manager
  - name: baetyl-function-python36-bin
    path: var/db/baetyl/baetyl-function-python36
  - name: baetyl-video-infer-bin
    path: var/db/baetyl/baetyl-video-infer
