FROM hub.baidubce.com/openedge/openedge-function-node85:0.1.5-devel as devel

FROM node:8.16-stretch-slim

COPY --from=devel /node_modules /node_modules

COPY function_grpc_pb.js function_pb.js openedge-function-node85.js /bin/
RUN chmod +x /bin/openedge-function-node85.js
ENTRYPOINT ["openedge-function-node85.js"]
