FROM ubuntu:18.04 as base

RUN apt-get update \
        && apt-get install -y build-essential wget python \
        && wget https://nodejs.org/dist/v8.5.0/node-v8.5.0.tar.gz \
        && tar vxzf node-v8.5.0.tar.gz \
        && cd node-v8.5.0 \
        && ./configure --prefix=/package \
        && make \
        && make install \
        && cp -r /package/* /usr/local

WORKDIR /
COPY package.json /
RUN cd / \
        && npm install

