ARG VERSION=latest

FROM hub.baidubce.com/openedgedev/openedge-function-python36:${VERSION}-opencv4-devel as devel

FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y software-properties-common --no-install-recommends gcc g++ python3 python3-opencv && \
    rm -rf /var/lib/apt/lists/*

COPY --from=devel /usr/local/lib/python3.6/dist-packages /usr/local/lib/python3.6/dist-packages/
COPY openedge-function-python36.py function_pb2.py function_pb2_grpc.py /bin/
ENTRYPOINT ["openedge-function-python36.py"]