FROM hub.baidubce.com/openedge/openedge-function-python27:0.1.5-devel as devel

FROM ubuntu:18.04
RUN apt-get update \
        && apt-get install -y python2.7 --no-install-recommends \
        && ln -s /usr/bin/python2.7 /usr/bin/python \
        && rm -rf /var/lib/apt/lists/*

COPY --from=devel /usr/local/lib/python2.7/dist-packages /usr/local/lib/python2.7/site-packages

COPY openedge-function-python27.py function_pb2.py function_pb2_grpc.py /bin/
RUN chmod +x /bin/openedge-function-python27.py
ENTRYPOINT ["openedge-function-python27.py"]

