FROM ubuntu:18.04

RUN apt-get update \
        && apt-get install -y gcc g++ python3 --no-install-recommends \
        && ln -s /usr/bin/python3 /usr/bin/python \
        && apt-get install -y python3-pip \
        && pip3 install -U pip \
        && pip install pyyaml protobuf grpcio \
        && rm -rf /var/lib/apt/lists/*
        