FROM hub.baidubce.com/openedge/openedge-function-python27:0.1.5-devel

COPY openedge-function-python27.py function_pb2.py function_pb2_grpc.py /bin/
RUN chmod +x /bin/openedge-function-python27.py
ENTRYPOINT ["openedge-function-python27.py"]
