FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get -y --no-install-recommends install \
        zip unzip cmake curl \
        pkg-config ca-certificates build-essential \
#       libgtk2.0-dev \
        libavcodec-dev libavformat-dev libswscale-dev \
        libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev \
        python3-dev python3-setuptools python3-pip && \
    pip3 install wheel numpy pyyaml protobuf grpcio

RUN mkdir -p /tmp/opencv && \
    cd /tmp/opencv && \
	curl -Lo opencv.zip https://openedge-resources.cdn.bcebos.com/opencv/opencv/archive/4.1.0.zip && \
	unzip -q opencv.zip
#	curl -Lo opencv_contrib.zip https://openedge-resources.cdn.bcebos.com/opencv/opencv_contrib/archive/4.1.0.zip && \
#	unzip -q opencv_contrib.zip

RUN mkdir -p /tmp/opencv/opencv-4.1.0/build && \
	cd /tmp/opencv/opencv-4.1.0/build && \
	cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local \
#       -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv/opencv_contrib-4.1.0/modules \
        -D BUILD_opencv_highgui=OFF \
        -D BUILD_DOCS=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF \
        -D BUILD_opencv_java=NO -D BUILD_opencv_python=NO -D BUILD_opencv_python2=NO \
        -D BUILD_opencv_python3=ON \
        -D WITH_JASPER=OFF \
        -D OPENCV_GENERATE_PKGCONFIG=ON ..  && \
	make -j4  && \
	make preinstall  && \
    make install  && \
	ldconfig  && \
    rm -rf /tmp/opencv
