FROM hub.baidubce.com/openedgedev/openedge-function-python36:0.1.5-devel
WORKDIR /
COPY openedge-function-python36.py function_pb2.py function_pb2_grpc.py /bin/
RUN chmod +x /bin/openedge-function-python36.py
ENTRYPOINT ["openedge-function-python36.py"]
