sudo: false

language: go

go:
  - 1.10.1

install: true
script:
  - echo "openedge build begin"
  - make
  - echo "openedge build end"
  - echo "openedge uint test begin"
  - make test
  - echo "openedge unit test end"
