#### server
## 如果要开放 GRPC 服务给客户端直接访问，需配置服务地址，如果不配置则不启动 GRPC 服务。
## If you want to open the GRPC service to the client for direct access,
## you need to configure the service address.
## If not configured, the GRPC service will not be started.
####
server: 

  ## GRPC 服务地址，举例：0.0.0.0:50051。
  ## The GRPC service address, e.g. 0.0.0.0:50051.
  address: 0.0.0.0:50051

  ## 最大并发连接数，默认不限制。
  ## Maximum number of concurrent connections, no limit by default.
  #concurrent:
  #  max: 0

  ## 最大消息长度，默认 4m。
  ## Maximum number of message length, 4m by default.
  #message:
  #  length:
  #    max: 4m

  ## 服务端证书，包括 CA 证书、私钥和公钥的路径。
  ## Server certificate, including the path to the CA certificate, private key and public key.
  #ca: var/db/baetyl/cert/ca.pem
  #key: var/db/baetyl/cert/server.pem
  #cert: var/db/baetyl/cert/server.key

hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
functions:
  - name: analyse
    service: function-python
    instance:
      max: 10
  - name: mark
    service: function-python
    instance:
      max: 10
rules:
  - clientid: function-mark-1
    subscribe:
      topic: video/infer/result
    function:
      name: mark
    publish:
      topic: video/infer/mark
logger:
  path: var/log/baetyl/service.log
  level: "debug"
