#### server
## 如果要开放 GRPC 服务给客户端直接访问，需配置服务地址，如果不配置则不启动 GRPC 服务。
## If you want to open the GRPC service to the client for direct access,
## you need to configure the service address.
## If not configured, the GRPC service will not be started.
####
server: 

  ## GRPC 服务地址，建议不对外暴露（举例：127.0.0.1:50051），如需暴露请开启证书认证（举例：0.0.0.0:50051）。
  ## The GRPC service address is not recommended for external exposure (e.g. 127.0.0.1:50051).
  ## If you need to expose it, please open the certificate (e.g. 0.0.0.0:50051).
  address: 127.0.0.1:50051

  ## 最大并发连接数，默认不限制。
  ## Maximum number of concurrent connections, no limit by default.
  #concurrent:
  #  max: 0

  ## 最大消息长度，默认 4m。
  ## Maximum number of message length, 4m by default.
  #message:
  #  length:
  #    max: 4m

  ## 服务端证书，包括 CA 证书、私钥和公钥的路径。
  ## Server certificate, including the path to the CA certificate, private key and public key.
  #ca: var/db/openedge/cert/ca.pem
  #key: var/db/openedge/cert/server.pem
  #cert: var/db/openedge/cert/server.key

hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
rules:
  - clientid: localfunc-1
    subscribe:
      topic: t
    function:
      name: python27-sayhi
    publish:
      topic: t/python2
  # - clientid: localfunc-2
  #   subscribe:
  #     topic: t
  #     qos: 1
  #   function:
  #     name: filter
  #   publish:
  #     topic: t/f
  #     qos: 1
  - clientid: localfunc-3
    subscribe:
      topic: t
    function:
      name: python36-sayhi
    publish:
      topic: t/python3
  - clientid: localfunc-4
    subscribe:
      topic: t
    function:
      name: node85-sayhi
    publish:
      topic: t/node8
functions:
  - name: python27-sayhi
    service: function-python27-sayhi
    instance:
      min: 0
      max: 10
      idletime: 1m
  # - name: filter
  #   service: function-filter
  #   instance:
  #     min: 1
  #     max: 10
  - name: python36-sayhi
    service: function-python36-sayhi
    instance:
      min: 0
      max: 10
      idletime: 1m
  - name: node85-sayhi
    service: function-node85-sayhi
    instance:
      min: 0
      max: 10
      idletime: 1m
logger:
  path: var/log/openedge/service.log
  level: "debug"
