hub:
  address: tcp://:1883
  username: test
  password: hahaha
rules:
  - clientid: localfunc-1
    subscribe:
      topic: t
    function:
      name: sayhi
    publish:
      topic: t/hi
  # - clientid: localfunc-2
  #   subscribe:
  #     topic: t
  #     qos: 1
  #   function:
  #     name: filter
  #   publish:
  #     topic: t/f
  #     qos: 1
  - clientid: localfunc-3
    subscribe:
      topic: t
    function:
      name: sayhi3
    publish:
      topic: t/hi3
functions:
  - name: sayhi
    service: function-sayhi
    instance:
      min: 0
      max: 10
      idletime: 1m
  # - name: filter
  #   service: function-filter
  #   instance:
  #     min: 1
  #     max: 10
  - name: sayhi3
    service: function-sayhi3
    instance:
      min: 0
      max: 10
      idletime: 1m
logger:
  path: var/log/openedge/service.log
  level: "debug"
