version: v0
services:
  - name: localhub
    image: openedge-hub
    replica: 1
    mounts:
      - name: localhub-conf
        path: etc/openedge
        readonly: true
      - name: localhub-cert
        path: var/db/openedge/cert
        readonly: true
      - name: localhub-data
        path: var/db/openedge/data
      - name: localhub-log
        path: var/log/openedge
      # native process mode only
      - name: openedge-hub-bin
        path: lib/openedge/openedge-hub
        readonly: true
  # - name: agent
  #   image: openedge-agent
  #   replica: 1
  #   mounts:
  #     - name: agent-conf
  #       path: etc/openedge
  #       readonly: true
  #     - name: agent-cert
  #       path: var/db/openedge/cert
  #       readonly: true
  #     - name: agent-volumes
  #       path: var/db/openedge/volumes
  #     - name: agent-log
  #       path: var/log/openedge
  #     # native process mode only
  #     - name: openedge-agent-bin
  #       path: lib/openedge/openedge-agent
  #       readonly: true
  # - name: remote-iothub
  #   image: openedge-remote-mqtt
  #   replica: 1
  #   mounts:
  #     - name: remote-iothub-conf
  #       path: etc/openedge
  #       readonly: true
  #     - name: remote-iothub-cert
  #       path: var/db/openedge/cert
  #       readonly: true
  #     - name: remote-iothub-log
  #       path: var/log/openedge
  #     # native process mode only
  #     - name: openedge-remote-mqtt-bin
  #       path: lib/openedge/openedge-remote-mqtt
  #       readonly: true
  - name: function-manager
    image: openedge-function-manager
    replica: 1
    mounts:
      - name: function-manager-conf
        path: etc/openedge
        readonly: true
      - name: function-manager-log
        path: var/log/openedge
      # native process mode only
      - name: openedge-function-manager-bin
        path: lib/openedge/openedge-function-manager
        readonly: true
  - name: function-sayhi
    image: openedge-function-python27
    replica: 0
    mounts:
      - name: function-sayhi-conf
        path: etc/openedge
        readonly: true
      - name: function-sayhi-code
        path: var/db/openedge/function-sayhi
        readonly: true
      # native process mode only
      - name: openedge-function-python27-bin
        path: lib/openedge/openedge-function-python27
        readonly: true
  # - name: function-filter
  #   image: openedge-function-sql
  #   replica: 0
  #   mounts:
  #     - name: function-filter-conf
  #       path: etc/openedge
  #       readonly: true
  #     # native process mode only
  #     - name: openedge-function-sql-bin
  #       path: lib/openedge/openedge-function-sql
  #       readonly: true
volumes:
  # hub
  - name: localhub-conf
    path: var/db/openedge/localhub-conf
  - name: localhub-data
    path: var/db/openedge/localhub-data
  - name: localhub-cert
    path: var/db/openedge/localhub-cert-only-for-test
  - name: localhub-log
    path: var/db/openedge/localhub-log
  # agent
  - name: agent-conf
    path: var/db/openedge/agent-conf
  - name: agent-cert
    path: var/db/openedge/agent-cert
  - name: agent-volumes
    path: var/db/openedge
  - name: agent-log
    path: var/db/openedge/agent-log
  # remote mqtt
  - name: remote-iothub-conf
    path: var/db/openedge/remote-iothub-conf
  - name: remote-iothub-cert
    path: var/db/openedge/remote-iothub-cert
  - name: remote-iothub-log
    path: var/db/openedge/remote-iothub-log
  # function
  - name: function-manager-conf
    path: var/db/openedge/function-manager-conf
  - name: function-manager-log
    path: var/db/openedge/function-manager-log
  - name: function-sayhi-conf
    path: var/db/openedge/function-sayhi-conf
  - name: function-sayhi-code
    path: var/db/openedge/function-sayhi-code
  - name: function-filter-conf
    path: var/db/openedge/function-filter-conf
  # bin, native process mode only
  - name: openedge-hub-bin
    path: var/db/openedge/openedge-hub
  - name: openedge-agent-bin
    path: var/db/openedge/openedge-agent
  - name: openedge-remote-mqtt-bin
    path: var/db/openedge/openedge-remote-mqtt
  - name: openedge-function-manager-bin
    path: var/db/openedge/openedge-function-manager
  - name: openedge-function-python27-bin
    path: var/db/openedge/openedge-function-python27
  - name: openedge-function-sql-bin
    path: var/db/openedge/openedge-function-sql
