version: v0
services:
  # - name: agent
  #   image: openedge-agent
  #   mounts:
  #     - name: agent-conf
  #       path: etc/openedge
  #       readonly: true
  #     - name: agent-cert
  #       path: var/db/openedge/cert
  #       readonly: true
  #     - name: agent-volumes
  #       path: var/db/openedge/volumes
  #     - name: agent-log
  #       path: var/log/openedge
  #     # native process mode only
  #     - name: agent-bin
  #       path: lib/openedge/openedge-agent
  #       readonly: true
  - name: localhub
    image: openedge-hub
    mounts:
      - name: localhub-conf
        path: etc/openedge
        readonly: true
      - name: localhub-db
        path: var/db/openedge
      - name: localhub-log
        path: var/log/openedge
      # native process mode only
      - name: localhub-bin
        path: lib/openedge/openedge-hub
        readonly: true
volumes:
  # agent's volumes
  - name: agent-conf
    path: var/db/openedge/agent-conf
  - name: agent-cert
    path: var/db/openedge/agent-cert
  - name: agent-volumes
    path: var/db/openedge
  - name: agent-log
    path: var/log/openedge/agent
  - name: agent-bin
    path: var/db/openedge/agent-bin
  # hub's volumes
  - name: localhub-conf
    path: var/db/openedge/localhub-conf
  - name: localhub-bin
    path: var/db/openedge/localhub-bin
  - name: localhub-db
    path: var/db/openedge/localhub-db
  - name: localhub-log
    path: var/log/openedge/localhub
