engine:
  kind: native
cert:
  ca: var/lib/baetyl/cert/sync/ca.pem
  key: var/lib/baetyl/cert/sync/client.key
  cert: var/lib/baetyl/cert/sync/client.pem
  insecureSkipVerify: true
httplink:
  http:
    address: https://sync.edge.baidubce.com
logger:
#  filename: var/log/baetyl/service.log
  level: debug
  encoding: console