openedge-function-runtime-node-image:
	@echo "build ${GOFLAG} $@"
	docker build -t openedge-function-runtime-node85:build -f Dockerfile85 ..
	docker build -t openedge-function-runtime-node611:build -f Dockerfile611 ..
	docker build -t openedge-function-runtime-node1015:build -f Dockerfile1015 ..