# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import openedge_function_runtime_pb2 as openedge__function__runtime__pb2


class RuntimeStub(object):
  """The runtime definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Handle = channel.unary_unary(
        '/runtime.Runtime/Handle',
        request_serializer=openedge__function__runtime__pb2.Message.SerializeToString,
        response_deserializer=openedge__function__runtime__pb2.Message.FromString,
        )


class RuntimeServicer(object):
  """The runtime definition.
  """

  def Handle(self, request, context):
    """Handle handles request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Handle': grpc.unary_unary_rpc_method_handler(
          servicer.Handle,
          request_deserializer=openedge__function__runtime__pb2.Message.FromString,
          response_serializer=openedge__function__runtime__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'runtime.Runtime', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
