hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
remotes:
  - name: iothub
    address: 'ssl://sandbox.mqtt.iot.bj.baidubce.com:8884'
    clientid: 11dd7422353c46fc8851ef8fb7114533
    username: xxxe1e0/test
    ca: var/db/baetyl/cert/ca.pem
    cert: var/db/baetyl/cert/client.pem
    key: var/db/baetyl/cert/client.key
rules:
  - hub:
      subscriptions:
        - topic: t
    remote:
      name: iothub
      subscriptions:
        - topic: t/remote
          qos: 1
logger:
  path: var/log/baetyl/service.log
  level: "debug"
