// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Persisted struct {
	QOS                  uint32   `protobuf:"varint,1,opt,name=QOS,proto3" json:"QOS,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	ClientID             string   `protobuf:"bytes,4,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Persisted) Reset()         { *m = Persisted{} }
func (m *Persisted) String() string { return proto.CompactTextString(m) }
func (*Persisted) ProtoMessage()    {}
func (*Persisted) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f40bb01bdb0366e4, []int{0}
}
func (m *Persisted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persisted.Unmarshal(m, b)
}
func (m *Persisted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persisted.Marshal(b, m, deterministic)
}
func (dst *Persisted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persisted.Merge(dst, src)
}
func (m *Persisted) XXX_Size() int {
	return xxx_messageInfo_Persisted.Size(m)
}
func (m *Persisted) XXX_DiscardUnknown() {
	xxx_messageInfo_Persisted.DiscardUnknown(m)
}

var xxx_messageInfo_Persisted proto.InternalMessageInfo

func (m *Persisted) GetQOS() uint32 {
	if m != nil {
		return m.QOS
	}
	return 0
}

func (m *Persisted) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Persisted) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Persisted) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type Transferred struct {
	Persisted            *Persisted `protobuf:"bytes,1,opt,name=Persisted,proto3" json:"Persisted,omitempty"`
	FunctionName         string     `protobuf:"bytes,2,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	FunctionInvokeID     string     `protobuf:"bytes,3,opt,name=FunctionInvokeID,proto3" json:"FunctionInvokeID,omitempty"`
	FunctionInstanceID   string     `protobuf:"bytes,4,opt,name=FunctionInstanceID,proto3" json:"FunctionInstanceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transferred) Reset()         { *m = Transferred{} }
func (m *Transferred) String() string { return proto.CompactTextString(m) }
func (*Transferred) ProtoMessage()    {}
func (*Transferred) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f40bb01bdb0366e4, []int{1}
}
func (m *Transferred) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transferred.Unmarshal(m, b)
}
func (m *Transferred) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transferred.Marshal(b, m, deterministic)
}
func (dst *Transferred) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transferred.Merge(dst, src)
}
func (m *Transferred) XXX_Size() int {
	return xxx_messageInfo_Transferred.Size(m)
}
func (m *Transferred) XXX_DiscardUnknown() {
	xxx_messageInfo_Transferred.DiscardUnknown(m)
}

var xxx_messageInfo_Transferred proto.InternalMessageInfo

func (m *Transferred) GetPersisted() *Persisted {
	if m != nil {
		return m.Persisted
	}
	return nil
}

func (m *Transferred) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *Transferred) GetFunctionInvokeID() string {
	if m != nil {
		return m.FunctionInvokeID
	}
	return ""
}

func (m *Transferred) GetFunctionInstanceID() string {
	if m != nil {
		return m.FunctionInstanceID
	}
	return ""
}

func init() {
	proto.RegisterType((*Persisted)(nil), "common.Persisted")
	proto.RegisterType((*Transferred)(nil), "common.Transferred")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_f40bb01bdb0366e4) }

var fileDescriptor_message_f40bb01bdb0366e4 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x89, 0xd5, 0xea, 0x4e, 0x5b, 0xa8, 0x83, 0x87, 0xe0, 0x69, 0xd9, 0xd3, 0xe2, 0x61,
	0x05, 0x7d, 0x04, 0x8b, 0xb0, 0x17, 0xad, 0xb1, 0x2f, 0x10, 0xb3, 0xa3, 0x04, 0x9b, 0x4c, 0x49,
	0xa2, 0xe0, 0xcb, 0xf9, 0x6c, 0x62, 0x6a, 0xd7, 0x15, 0x7b, 0xcb, 0xf7, 0xff, 0x84, 0xff, 0x63,
	0x60, 0xe6, 0x28, 0x46, 0xfd, 0x42, 0xcd, 0x26, 0x70, 0x62, 0x1c, 0x1b, 0x76, 0x8e, 0x7d, 0x65,
	0xa1, 0x58, 0x52, 0x88, 0x36, 0x26, 0xea, 0x70, 0x0e, 0xa3, 0x87, 0xfb, 0x47, 0x29, 0x4a, 0x51,
	0xcf, 0xd4, 0xf7, 0x13, 0xcf, 0xe0, 0x68, 0xc5, 0x1b, 0x6b, 0xe4, 0x41, 0x29, 0xea, 0x42, 0x6d,
	0x01, 0x25, 0x1c, 0x2f, 0xf5, 0xc7, 0x9a, 0x75, 0x27, 0x47, 0xa5, 0xa8, 0xa7, 0x6a, 0x87, 0x78,
	0x0e, 0x27, 0x37, 0x6b, 0x4b, 0x3e, 0xb5, 0x0b, 0x79, 0x98, 0xbf, 0xf4, 0x5c, 0x7d, 0x0a, 0x98,
	0xac, 0x82, 0xf6, 0xf1, 0x99, 0x42, 0xa0, 0x0e, 0x2f, 0x07, 0xd3, 0x79, 0x73, 0x72, 0x75, 0xda,
	0x6c, 0xb5, 0x9a, 0xbe, 0x50, 0x03, 0xbd, 0x0a, 0xa6, 0xb7, 0x6f, 0xde, 0x24, 0xcb, 0xfe, 0x4e,
	0x3b, 0xfa, 0x71, 0xfa, 0x93, 0xe1, 0x05, 0xcc, 0x77, 0xdc, 0xfa, 0x77, 0x7e, 0xa5, 0x76, 0x91,
	0x1d, 0x0b, 0xf5, 0x2f, 0xc7, 0x06, 0xf0, 0x37, 0x8b, 0x49, 0x7b, 0x43, 0xbd, 0xf6, 0x9e, 0xe6,
	0x69, 0x9c, 0x4f, 0x77, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xba, 0xae, 0x40, 0x52, 0x4b, 0x01,
	0x00, 0x00,
}
