functions:
  - name: 'sayhi'
    handler: 'index.handler'
    codedir: 'var/db/openedge/function-sayhi'
  - name: 'sayhi3'
    handler: 'index.handler'
    codedir: 'var/db/openedge/function-sayhi'
logger:
  path: var/log/openedge/service.log
  level: "debug"