FROM hub.baidubce.com/baetyl-beta/baetyl-openvino:0.1.6-gocv41-devel as devel

FROM ubuntu:16.04

# OpemVINO 2019.2.242
# TODO: remove useless files
COPY --from=devel /opt/intel /opt/intel

ENV INTEL_OPENVINO_DIR "/opt/intel/openvino"
ENV INTEL_CVSDK_DIR "${INTEL_OPENVINO_DIR}"
ENV HDDL_INSTALL_DIR "${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/external/hddl"
ENV LD_LIBRARY_PATH "${INTEL_CVSDK_DIR}/opencv/lib:/opt/intel/opencl:${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/external/hddl/lib:${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/external/gna/lib:${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/external/mkltiny_lnx/lib:${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/external/tbb/lib:${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/lib/intel64:${INTEL_OPENVINO_DIR}/openvx/lib"
ENV PATH "${INTEL_OPENVINO_DIR}/deployment_tools/model_optimizer:${PATH}"
ENV OpenCV_DIR "${INTEL_CVSDK_DIR}/opencv/cmake"

ENV CGO_CXXFLAGS "--std=c++11"
ENV CGO_CPPFLAGS "-I${INTEL_CVSDK_DIR}/opencv/include -I${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/include"
ENV CGO_LDFLAGS "-L${INTEL_CVSDK_DIR}/opencv/lib -L${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64 -lpthread -ldl -lHeteroPlugin -lMKLDNNPlugin -lmyriadPlugin -linference_engine -lclDNNPlugin -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d -lopencv_flann -lopencv_gapi -lopencv_ml -lopencv_photo -lopencv_stitching -lopencv_videoio_ffmpeg -lopencv_videoio_gstreamer -lopencv_videoio_intel_mfx"
ENV PKG_CONFIG_PATH /usr/lib64/pkgconfig
ENV PATH "${PATH}:/usr/local/go/bin"
ENV GOPATH /root/go

RUN cd ${INTEL_OPENVINO_DIR}/install_dependencies && \
    ./install_openvino_dependencies.sh && \
    ./install_NEO_OCL_driver.sh

COPY baetyl-video-infer /bin/
ENTRYPOINT ["baetyl-video-infer"]