FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get -y --no-install-recommends install zip unzip golang pkg-config build-essential cmake curl git ca-certificates libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev

ENV GOPATH /root/go

RUN go get -u -d gocv.io/x/gocv && \
    cd $GOPATH/src/gocv.io/x/gocv && \
    sed -i "s/sudo //g" Makefile && \
    sed -i "s/github.com/baetyl-resources.cdn.bcebos.com/g" Makefile && \
    make download && \
    make build && \
    make sudo_install && \
    make clean && \
    make verify
