// Code generated by protoc-gen-go. DO NOT EDIT.
// source: function.proto

package openedge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FunctionMessage function message
type FunctionMessage struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QOS                  uint32   `protobuf:"varint,2,opt,name=QOS,proto3" json:"QOS,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	FunctionName         string   `protobuf:"bytes,11,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	FunctionInvokeID     string   `protobuf:"bytes,12,opt,name=FunctionInvokeID,proto3" json:"FunctionInvokeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionMessage) Reset()         { *m = FunctionMessage{} }
func (m *FunctionMessage) String() string { return proto.CompactTextString(m) }
func (*FunctionMessage) ProtoMessage()    {}
func (*FunctionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{0}
}

func (m *FunctionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionMessage.Unmarshal(m, b)
}
func (m *FunctionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionMessage.Marshal(b, m, deterministic)
}
func (m *FunctionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionMessage.Merge(m, src)
}
func (m *FunctionMessage) XXX_Size() int {
	return xxx_messageInfo_FunctionMessage.Size(m)
}
func (m *FunctionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionMessage proto.InternalMessageInfo

func (m *FunctionMessage) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *FunctionMessage) GetQOS() uint32 {
	if m != nil {
		return m.QOS
	}
	return 0
}

func (m *FunctionMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *FunctionMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FunctionMessage) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *FunctionMessage) GetFunctionInvokeID() string {
	if m != nil {
		return m.FunctionInvokeID
	}
	return ""
}

func init() {
	proto.RegisterType((*FunctionMessage)(nil), "openedge.FunctionMessage")
}

func init() { proto.RegisterFile("function.proto", fileDescriptor_8ac74addf543d91a) }

var fileDescriptor_8ac74addf543d91a = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xcd, 0x4b,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2f, 0x48, 0xcd,
	0x4b, 0x4d, 0x49, 0x4f, 0x55, 0xda, 0xcc, 0xc8, 0xc5, 0xef, 0x06, 0x95, 0xf4, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x15, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09,
	0x62, 0xf2, 0x74, 0x11, 0x12, 0xe0, 0x62, 0x0e, 0xf4, 0x0f, 0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x0d, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0x43, 0xf2, 0x0b, 0x32, 0x93, 0x25, 0x98, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x09, 0x2e, 0xf6, 0x80, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14,
	0x09, 0x16, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x57, 0x48, 0x89, 0x8b, 0x07, 0x66, 0x89, 0x5f,
	0x62, 0x6e, 0xaa, 0x04, 0x37, 0x58, 0x1b, 0x8a, 0x98, 0x90, 0x16, 0x97, 0x00, 0x8c, 0xef, 0x99,
	0x57, 0x96, 0x9f, 0x9d, 0xea, 0xe9, 0x22, 0xc1, 0x03, 0x56, 0x87, 0x21, 0x6e, 0xe4, 0xc5, 0xc5,
	0x01, 0x13, 0x13, 0xb2, 0xe3, 0x62, 0x71, 0x4e, 0xcc, 0xc9, 0x11, 0x92, 0xd4, 0x83, 0x79, 0x4a,
	0x0f, 0xcd, 0x43, 0x52, 0xb8, 0xa5, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x41, 0x62, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0x22, 0x9a, 0x99, 0x24, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FunctionClient is the client API for Function service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionClient interface {
	Call(ctx context.Context, in *FunctionMessage, opts ...grpc.CallOption) (*FunctionMessage, error)
}

type functionClient struct {
	cc *grpc.ClientConn
}

func NewFunctionClient(cc *grpc.ClientConn) FunctionClient {
	return &functionClient{cc}
}

func (c *functionClient) Call(ctx context.Context, in *FunctionMessage, opts ...grpc.CallOption) (*FunctionMessage, error) {
	out := new(FunctionMessage)
	err := c.cc.Invoke(ctx, "/openedge.Function/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServer is the server API for Function service.
type FunctionServer interface {
	Call(context.Context, *FunctionMessage) (*FunctionMessage, error)
}

func RegisterFunctionServer(s *grpc.Server, srv FunctionServer) {
	s.RegisterService(&_Function_serviceDesc, srv)
}

func _Function_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openedge.Function/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Call(ctx, req.(*FunctionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Function_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openedge.Function",
	HandlerType: (*FunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Function_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "function.proto",
}
