version: V0
services:
  # - name: agent
  #   image: 'openedge-agent'
  #   mounts:
  #     - volume: var/db/openedge/service/cert-igeblfrt8
  #       target: /cert
  #       readonly: true
  - name: localhub
    image: 'openedge-hub'
    expose:
      - '1883:1883'
    mounts:
      - volume: var/db/openedge/volume/localhub
        target: /var/db/openedge
  # - name:localfunc
  #   image: 'openedge-function'
