FROM golang:alpine as builder
RUN apk add --update --no-cache make
COPY openedge /go/src/github.com/baidu/openedge
WORKDIR /go/src/github.com/baidu/openedge/
RUN make release-test GOOS=linux GOARCH=amd64