hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
  clientid: timer-1
timer:
  interval: 10s
publish:
  topic: t
  payload: "{\"timestamp\": {{.Time.NowUnixNano}},\"Rand.Intn\": {{.Rand.Intn 10}},\"Rand.Float64n\": {{.Rand.Float64n 60}},\"anyString\": \"inputString\"}"
logger:
  path: var/log/baetyl/service.log
  level: "debug"
