hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
  clientid: timer-1
timer:
  interval: 10s
publish:
  topic: t
  payload: "{\"timestamp\": {{.Time.TE}},\"temperature\": {{.Rand.RD}},\"humidity\": {{.Frand.FD}},\"example\": \"anything\"}"
logger:
  path: var/log/baetyl/service.log
  level: "debug"
