hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
  clientid: timer-1
timer:
  interval: 10s
publish:
  topic: t
  payload: "{\"timestamp\": {{.Time.NowUnixNano}}}"
logger:
  path: var/log/baetyl/service.log
  level: "debug"
