remote:
  mqtt:
    clientid: 5aa11f8429c84a40bae4cd41b09dc4c9
    address: "ssl://sandbox.mqtt.iot.bj.baidubce.com:8884"
    username: e45c13c9d71c4ab5bf76448f01a52b3b/5aa11f8429c84a40bae4cd41b09dc4c9
    ca: var/db/openedge/cert/root.pem
    cert: var/db/openedge/cert/client.pem
    key: var/db/openedge/cert/client.key
  http:
    ca: var/db/openedge/cert/openapi.pem
    address: "https://iot-edge.baidu-int.com"
  meta:
    cert: v1
logger:
  path: var/log/openedge/service.log
  level: debug
