name: CI
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Use Node.js 8.5
        uses: actions/setup-node@v1
        with:
          node-version: 8.5

      - name: Install Dependencies
        run: |
          pip2 install grpcio protobuf pyyaml gevent grpcio-tools
          pip3 install grpcio protobuf pyyaml

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test GO_TEST_FLAGS=--race

      # - name: Upload Coverage report to CodeCov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build