name: image-develop
on:
  push:
    branches:
      - master

jobs:
  image:
    name: docker build baetyl image
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt update -y && sudo apt install -y qemu qemu-user-static
      - name: Install Docker CE for buildx
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install docker-ce
          docker -v
      - name: Checkout code
        uses: actions/checkout@v1
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_REGISTRY_ID }} -p ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: build and publish baetyl image
        run: |
          make image PLATFORMS=all XFLAGS='--push --cache-to=type=local,dest=/tmp/baetyl' REGISTRY=baetyltechtest/

  package:
    name: packages for native mode
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v1
      - id: version
        run: |
          echo ::set-output name=version::git-$(git rev-parse --short HEAD)
      - name: build
        run: make build PLATFORMS=all
      - uses: actions/upload-artifact@v2
        with:
          name: baetyl_darwin-amd64_${{ steps.version.outputs.version }}
          path: output/darwin/amd64/baetyl/*
      - uses: actions/upload-artifact@v2
        with:
          name: baetyl_linux-amd64_${{ steps.version.outputs.version }}
          path: output/linux/amd64/baetyl/*
      - uses: actions/upload-artifact@v2
        with:
          name: baetyl_linux-arm-v7_${{ steps.version.outputs.version }}
          path: output/linux/arm/v7/baetyl/*
      - uses: actions/upload-artifact@v2
        with:
          name: baetyl_linux-arm64_${{ steps.version.outputs.version }}
          path: output/linux/arm64/baetyl/*


          