name: test-pack
on: 
  push:
    tags:
jobs:
  amd64:
    name: build on amd64
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - id: version
        run: |
          echo ::set-output name=version::$(git tag --contains HEAD)
      - uses: baetyl/run-on-arch-action@master
        with:
          architecture: amd64
          run: |
            apt update
            apt-get install -y dh-make dh-systemd
            cp -r scripts/debian/ debian/
            sed -i "s/@version@/${{ steps.version.outputs.version }}/g; s/@revision@/1/g" debian/changelog
            sed -i "s/level: debug//g;" example/docker/etc/baetyl/conf.yml
            dpkg-buildpackage -b -d -uc -us -i
            cp ../baetyl_${{ steps.version.outputs.version }}-1_amd64.deb .
      - id: path
        run: echo ::set-output name=path::$(pwd)/baetyl_${{ steps.version.outputs.version }}-1_amd64.deb
      - uses: actions/upload-artifact@v1
        with:
          name: baetyl-amd64
          path: ${{ steps.path.outputs.path }}
          
  armv7:
      name: build on armv7
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v1
        - id: version
          run: |
            echo ::set-output name=version::$(git tag --contains HEAD)
        - uses: baetyl/run-on-arch-action@master
          with:
            architecture: armv7
            run: |
              apt update
              apt-get install -y dh-make dh-systemd
              cp -r scripts/debian/ debian/
              sed -i "s/@version@/${{ steps.version.outputs.version }}/g; s/@revision@/1/g" debian/changelog
              sed -i "s/level: debug//g;" example/docker/etc/baetyl/conf.yml
              dpkg-buildpackage -b -d -uc -us -i
              cp ../baetyl_${{ steps.version.outputs.version }}-1_armhf.deb .
        - id: path
          run: echo ::set-output name=path::$(pwd)/baetyl_${{ steps.version.outputs.version }}-1_armhf.deb
        - uses: actions/upload-artifact@v1
          with:
            name: baetyl-armv7
            path: ${{ steps.path.outputs.path }}
  
  i386:
    name: build on i386
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - id: version
        run: |
          echo ::set-output name=version::$(git tag --contains HEAD)
      - uses: baetyl/run-on-arch-action@master
        with:
          architecture: i386
          run: |
            apt update
            apt-get install -y dh-make dh-systemd
            cp -r scripts/debian/ debian/
            sed -i "s/@version@/${{ steps.version.outputs.version }}/g; s/@revision@/1/g" debian/changelog
            sed -i "s/level: debug//g;" example/docker/etc/baetyl/conf.yml
            dpkg-buildpackage -b -d -uc -us -i
            cp ../baetyl_${{ steps.version.outputs.version }}-1_i386.deb .
      - id: path
        run: echo ::set-output name=path::$(pwd)/baetyl_${{ steps.version.outputs.version }}-1_i386.deb
      - uses: actions/upload-artifact@v1
        with:
          name: baetyl-i386
          path: ${{ steps.path.outputs.path }}
          
  arm64:
      name: build on arm64
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v1
        - id: version
          run: |
            echo ::set-output name=version::$(git tag --contains HEAD)
        - uses: baetyl/run-on-arch-action@master
          with:
            architecture: arm64
            run: |
              apt update
              apt-get install -y dh-make dh-systemd
              cp -r scripts/debian/ debian/
              sed -i "s/@version@/${{ steps.version.outputs.version }}/g; s/@revision@/1/g" debian/changelog
              sed -i "s/level: debug//g;" example/docker/etc/baetyl/conf.yml
              dpkg-buildpackage -b -d -uc -us -i
              cp ../baetyl_${{ steps.version.outputs.version }}-1_arm64.deb .
        - id: path
          run: echo ::set-output name=path::$(pwd)/baetyl_${{ steps.version.outputs.version }}-1_arm64.deb
        - uses: actions/upload-artifact@v1
          with:
            name: baetyl-arm64
            path: ${{ steps.path.outputs.path }}

  centos:
      name: build on centos
      runs-on: ubuntu-18.04
      steps:
        - name: Setup Go
          uses: actions/setup-go@v1
          with:
            go-version: 1.13
        - name: Checkout code
          uses: actions/checkout@v1
        - name: Build
          run: make build
        - id: version
          run: |
            echo ::set-output name=version::$(git tag --contains HEAD)
        - name: prepare
          run: |
            sudo apt update && sudo apt install -y tree
            sed -i "s/level: debug//g;" example/docker/etc/baetyl/conf.yml
            sed -i "s/@version@/${{ steps.version.outputs.version }}/g" scripts/centos/baetyl.spec
            sed -i "s/@version@/${{ steps.version.outputs.version }}/g" scripts/centos/pack.sh
            mkdir baetyl-${{ steps.version.outputs.version }}
            cp -r baetyl example scripts baetyl-${{ steps.version.outputs.version }}
            tree baetyl-${{ steps.version.outputs.version }}
            tar -cvzf baetyl-${{ steps.version.outputs.version }}.tar.gz baetyl-${{ steps.version.outputs.version }}
            ls
        - name: centos pack
          uses: docker://centos:7
          with:
            entrypoint: /bin/bash
            args: "scripts/centos/pack.sh"
#         - id: path
#           run: echo ::set-output name=path::$(pwd)/baetyl_${{ steps.version.outputs.version }}-1_arm64.deb
#         - uses: actions/upload-artifact@v1
#           with:
#             name: baetyl-arm64
#             path: ${{ steps.path.outputs.path }}
